// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwSzfG5NazORAF25eroHGd1zLXIrQsFtY',
    appId: '1:378570903105:web:b23ac764b9aa23cf11c0c0',
    messagingSenderId: '378570903105',
    projectId: 'cattle-breeding-67448',
    authDomain: 'cattle-breeding-67448.firebaseapp.com',
    storageBucket: 'cattle-breeding-67448.firebasestorage.app',
    measurementId: 'G-TH7XHJZCPV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAl7kS6-WgI_K1Ma7CVhtyLz5mHZIqMJ0U',
    appId: '1:378570903105:android:fa44c0f8ca0bf42911c0c0',
    messagingSenderId: '378570903105',
    projectId: 'cattle-breeding-67448',
    storageBucket: 'cattle-breeding-67448.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApFoOUDpFcepBbqo1oovkBQ5LZpDoSJcg',
    appId: '1:378570903105:ios:2febcf01b02a783411c0c0',
    messagingSenderId: '378570903105',
    projectId: 'cattle-breeding-67448',
    storageBucket: 'cattle-breeding-67448.firebasestorage.app',
    iosBundleId: 'com.example.cattleApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApFoOUDpFcepBbqo1oovkBQ5LZpDoSJcg',
    appId: '1:378570903105:ios:2febcf01b02a783411c0c0',
    messagingSenderId: '378570903105',
    projectId: 'cattle-breeding-67448',
    storageBucket: 'cattle-breeding-67448.firebasestorage.app',
    iosBundleId: 'com.example.cattleApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCwSzfG5NazORAF25eroHGd1zLXIrQsFtY',
    appId: '1:378570903105:web:6c4bfee50bbd8b3711c0c0',
    messagingSenderId: '378570903105',
    projectId: 'cattle-breeding-67448',
    authDomain: 'cattle-breeding-67448.firebaseapp.com',
    storageBucket: 'cattle-breeding-67448.firebasestorage.app',
    measurementId: 'G-6ZYS8ER76B',
  );
}
